spring:
    application:
        name: ace-center

server:
    port: 8761 #启动端口

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false  #是否获取eureka服务器注册表上的注册信息，默认为true时，可以启动，但报异常：Cannot execute request on any known server
    server:
      enable-self-preservation: false  # 关闭自我保护模式